import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const googleFont = Poppins({
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={googleFont.className}>{children}</body>
    </html>
  )
}
